POST http://localhost:3510/addUser
Content-Type: application/json

{
    "username": "Hassan2",
    "email": "hassan2@gmail.com",
    "password": "1234",
    "role": "user"
}

###

POST http://localhost:3510/addProject
Content-Type: application/json

{
    "title": "Project 1",
    "shortDescription": "This is project 1",
    "description": "This is project 1",
    "period" : 4,
    "thumbnail": "https://www.google.com",
    "ImagesList": ["https://www.google.com", "https://www.google.com"],
    "Tags": ["tag1", "tag2"]
}
###

POST http://localhost:3510/login
Content-Type: application/json

{
    "email": "hassan2@gmail.com",
    "password": "1234"
}


# @baseUrl = "http://localhost:3510/login"
# # Login
# # @name tokenAPI
# POST {{baseUrl}}/Auth/login HTTP/1.1
# Content-Type: application/json

# {
#     "Username": "Hassan2",
#     "Password": "1234"
# }
# ###

# @authToken = {{tokenAPI.response.body.token}}
# # Get User
# # @name getUser
# GET {{baseUrl}}/User
# Authorization: Bearer {{authToken}}