@baseUrl = http://localhost:3510

# GET {{baseUrl}}

###

POST {{baseUrl}}/addUser
Content-Type: application/json

{
    "username": "Hassan3",
    "email": "hassan3@gmail.com",
    "password": "1234",
    "role": "admin"
}

###
# Login
# @name TokenJWT
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "hassan3@gmail.com",
    "password": "1234"
}

# {
#     "email": "hassan2@gmail.com",
#     "password": "1234"
# }

###
@authToken = {{TokenJWT.response.body.accessToken}}
DELETE  {{baseUrl}}/projects/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
@authToken = {{TokenJWT.response.body.accessToken}}
POST {{baseUrl}}/addProject
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "projectID": 6,
    "title": "Grandmaster's Gambit: The Ultimate Chess Experience",
    "shortDescription": "Grandmaster's Gambit is an immersive and feature-rich chess game project aimed at providing players with the ultimate chess experience. Whether you're a beginner learning the basics or a seasoned grandmaster looking for a challenge, this game has something for everyone",
    "description": "Grandmaster's Gambit is an immersive and feature-rich chess game project aimed at providing players with the ultimate chess experience. Whether you're a beginner learning the basics or a seasoned grandmaster looking for a challenge, this game has something for everyone",
    "period" : 5,
    "thumbnail": "https://www.google.com",
    "ImagesList": ["https://www.google.com", "https://www.google.com"],
    "Tags": ["tag1", "tag2", "tag3"]
}

###
@authToken = {{TokenJWT.response.body.accessToken}}
POST {{baseUrl}}/addProject
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "projectID": 2,
    "title": "Project 6",
    "shortDescription": "This is project 6",
    "description": "This is project 6",
    "period" : 5,
    "thumbnail": "https://www.google.com",
    "ImagesList": ["https://www.google.com", "https://www.google.com"],
    "Tags": ["tag1", "tag2", "tag3"]
}


###
//@authToken = {{TokenJWT.response.body.accessToken}}
# Get List
# @name showProjectList
GET {{baseUrl}}/projects
//Authorization: Bearer {{authToken}}


###
GET {{baseUrl}}/projects/2
Content-Type: application/json

###
//@authToken = {{TokenJWT.response.body.accessToken}}
PUT {{baseUrl}}/projects/12/manageProject
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "nHAAAAASAAAN",
    "description": "HASSAAAAAN",
    "period" : 5,
    "thumbnail": "https://www.google.com",
    "ImagesList": ["https://www.google.com", "https://www.google.com"],
    "Tags": ["tag1", "tag2", "tag3"]
}

